export const industriesData: string[] = [
    "Aerospace & Defense",
    "Agriculture",
    "Arts, Entertainment & Recreation",
    "Construction, Repair & Maintenance Services",
    "Education",
    "Energy, Mining & Utilities",
    "Financial Services",
    "Government & Public Administration",
    "Healthcare",
    "Hotels & Travel Accommodation",
    "Human Resources & Staffing",
    "Information Technology",
    "Insurance",
    "Legal",
    "Management & Consulting",
    "Manufacturing",
    "Media & Communication",
    "Nonprofit & NGO",
    "Personal Consumer Services",
    "Pharmaceutical & Biotechnology",
    "Real Estate",
    "Restaurants & Food Service",
    "Retail & Wholesale",
    "Telecommunications",
    "Transportation & Logistics",
    "Farm Support",
    "Crop Production",
    "Culture & Entertainment",
    "Sports & Recreation",
    "Architectural & Engineering Services",
    "Construction",
    "Colleges & Universities",
    "Education & Training Services",
    "Primary & Secondary Schools",
    "Energy & Utilities",
    "Accounting & Tax",
    "Banking & Lending",
    "Financial Transaction Processing",
    "Stock Exchanges",
    "Investment & Asset Management",
    "National Agencies",
    "Municipal Agencies",
    "Health Care Services & Hospitals",
    "Hotels & Resorts",
    "Travel Agencies",
    "HR Consulting",
    "Computer Hardware Development",
    "Enterprise Software & Network Solutions",
    "Internet & Web Services",
    "Information Technology Support Services",
    "Insurance Agencies & Brokerages",
    "Insurance Carriers",
    "Building & Personnel Services",
    "Business Consulting",
    "Membership Organizations",
    "Research & Development",
    "Security & Protective",
    "Chemical Manufacturing",
    "Electronics Manufacturing",
    "Food & Beverage Manufacturing",
    "Health Care Products Manufacturing",
    "Machinery Manufacturing",
    "Transportation Equipment Manufacturing",
    "Consumer Product Manufacturing",
    "Advertising & Public Relations",
    "Film Production",
    "Publishing",
    "Broadcast Media",
    "Video Game Publishing",
    "Grantmaking & Charitable Foundations",
    "Religious Institutions",
    "Civic & Social Services",
    "Consumer Product Rental",
    "Beauty & Wellness",
    "Biotech & Pharmaceuticals",
    "Real Estate",
    "Catering & Food Service Contractors",
    "Restaurants & Cafes",
    "Office Supply & Copy Stores",
    "Wholesale",
    "Automotive Parts & Accessories Stores",
    "Beauty & Personal Accessories Stores",
    "Consumer Electronics & Appliances Stores",
    "Department, Clothing & Shoe Stores",
    "Drug & Health Stores",
    "Food & Beverage Stores",
    "General Merchandise & Superstores",
    "Home Furniture & Housewares Stores",
    "Other Retail Stores",
    "Pet & Pet Supplies Stores",
    "Sporting Goods Stores",
    "Toy & Hobby Stores",
    "Vehicle Dealers",
    "Grocery Stores",
    "Cable, Internet & Telephone Providers",
    "Telecommunications Services",
    "Rail Transportation",
    "Shipping & Trucking",
    "Car & Truck Rental",
    "Airlines, Airports & Air Transportation",
    "Taxi & Car Services",
  ];